"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Thomas Lazarus"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[signing]
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
behavior = "own"
backend = "ssh"

[revsets]
log = 'present(@) | ancestors(immutable_heads().., 2) | present(trunk()) | all()'

[ui]
graph.style = "ascii"
